# Generated by Django 2.2.4 on 2019-08-07 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_news'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='featuredtext',
            field=models.CharField(default=1, max_length=150),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='news',
            name='featuredtext_en',
            field=models.CharField(default=1, max_length=150),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='news',
            name='featuredtext_ru',
            field=models.CharField(default=1, max_length=150),
            preserve_default=False,
        ),
    ]
