# Generated by Django 2.2.4 on 2019-08-08 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_auto_20190807_1007'),
    ]

    operations = [
        migrations.CreateModel(
            name='Emails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('emailform', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': 'Email',
                'verbose_name_plural': 'Emaillər',
            },
        ),
    ]
